# Generated by Django 5.0 on 2024-02-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pise_basic_setup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_1", models.BooleanField()),
                ("group_2", models.BooleanField()),
                ("group_3", models.BooleanField()),
                ("group_4", models.BooleanField()),
                ("test_batch", models.BooleanField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pise_basic_setup.students",
                    ),
                ),
            ],
        ),
    ]
