# Generated by Django 5.0 on 2024-01-27 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pise_basic_setup", "0003_students_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="dob",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
