# Generated by Django 5.0 on 2024-02-03 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pise_basic_setup", "0004_remove_students_dob_remove_students_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
