# Generated by Django 5.0 on 2024-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pise_basic_setup", "0005_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="group_1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="students",
            name="group_2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="students",
            name="group_3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="students",
            name="group_4",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="students",
            name="test_batch",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="students",
            name="payment_status",
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name="Exams",
        ),
    ]
