# Generated by Django 5.0 on 2024-02-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pise_basic_setup",
            "0006_students_group_1_students_group_2_students_group_3_and_more",
        ),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="session_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sessions.session"
            ),
        ),
    ]
