# Generated by Django 5.0 on 2024-01-27 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pise_basic_setup", "0006_usersession_permitted_til"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="permitted_til",
            new_name="session_expiry",
        ),
    ]
