# Generated by Django 5.0 on 2024-01-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pise_basic_setup", "0007_rename_permitted_til_usersession_session_expiry"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="session_key",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sessions.session"
            ),
        ),
    ]
