# Generated by Django 5.0 on 2024-01-27 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pise_basic_setup", "0009_rename_session_key_usersession_session_key_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="session_key_id",
            new_name="session_key",
        ),
    ]
